import assert from 'node:assert/strict';
import {test} from 'node:test';
import express from 'express';
import 'pino-http';
import cookieParser from 'cookie-parser';
import {createDiagnosisReportPdfRouter} from '../src/routes/diagnosisReportPdf';
import {requireStaffAuth} from '../src/middleware/staffAuth';
import {StaffAuthService} from '../src/services/staffAuthService';
import {safeRequestError} from '../src/middleware/safeRequestError';
import {DiagnosisError} from '../src/domain/itManagementDiagnosis';
const cid='11111111-1111-4111-8111-111111111111',rid='22222222-2222-4222-8222-222222222222',unapproved='33333333-3333-4333-8333-333333333333',pending='44444444-4444-4444-8444-444444444444',corrupt='55555555-5555-4555-8555-555555555555',pdf=Buffer.from('%PDF-1.4\napi');
async function api(){const app=express(),auth=new StaffAuthService('test-key');const exists=(c:string,r:string)=>c===cid&&[rid,unapproved,pending,corrupt].includes(r);const service={generate:async(c:string,r:string)=>{if(!exists(c,r))throw new DiagnosisError(404,'NOT_FOUND');if(r===unapproved)throw new DiagnosisError(422,'PDF_REPORT_NOT_APPROVED');return {status:r===pending?'PENDING':'READY'}},status:async(c:string,r:string)=>{if(!exists(c,r))throw new DiagnosisError(404,'NOT_FOUND');return {status:r===pending?'PENDING':'READY'}},download:async(c:string,r:string)=>{if(!exists(c,r))throw new DiagnosisError(404,'NOT_FOUND');if(r===pending)throw new DiagnosisError(409,'PDF_NOT_READY');if(r===corrupt)throw new DiagnosisError(422,'DIAGNOSIS_REPORT_PDF_HASH_MISMATCH');return pdf}};app.use(cookieParser());app.use('/api/admin/it-management-diagnosis',requireStaffAuth(auth),createDiagnosisReportPdfRouter(service as never));app.use(safeRequestError);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const port=(server.address() as any).port,base=`http://127.0.0.1:${port}/api/admin/it-management-diagnosis`,cookie=`staff_session=${auth.issueSessionToken({email:'admin@test'})}`;return {base,cookie,close:()=>new Promise<void>(r=>server.close(()=>r()))};}
test('PDF admin API enforces auth, case/report scope and serves verified PDF',async()=>{const a=await api();try{assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${rid}/pdf`)).status,401);assert.equal((await fetch(`${a.base}/cases/${cid}/reports/66666666-6666-4666-8666-666666666666/pdf`,{method:'POST',headers:{Cookie:a.cookie}})).status,404);assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${rid}/pdf`,{method:'POST',headers:{Cookie:a.cookie}})).status,202);assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${rid}/pdf`,{headers:{Cookie:a.cookie}})).status,200);const d=await fetch(`${a.base}/cases/${cid}/reports/${rid}/pdf/download`,{headers:{Cookie:a.cookie}});assert.equal(d.status,200);assert.equal(d.headers.get('content-type'),'application/pdf');assert.deepEqual(Buffer.from(await d.arrayBuffer()),pdf);}finally{await a.close();}});
test('PDF admin API rejects unapproved, non-ready and hash-mismatched downloads',async()=>{const a=await api();try{const h={Cookie:a.cookie};assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${unapproved}/pdf`,{method:'POST',headers:h})).status,422);assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${pending}/pdf/download`,{headers:h})).status,409);assert.equal((await fetch(`${a.base}/cases/${cid}/reports/${corrupt}/pdf/download`,{headers:h})).status,422);}finally{await a.close();}});
