import assert from 'node:assert/strict';
import {after,before,test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {createDiagnosisHarness} from './support/diagnosisHarness';
import {DiagnosisHearingRepo} from '../src/services/diagnosisHearingRepo';
import {SURVEY_QUESTIONS,type Actor} from '../src/domain/itManagementDiagnosis';
import {buildInterviewAssistantContext} from '../src/services/interviewAssistantContext';
import {validateInterviewOutput} from '../src/domain/diagnosisWorkspace';
import {validateStructurerOutput} from '../src/domain/diagnosisReview';
import {managementAnalysisReadModel} from '../src/services/managementAnalysisReadModel';
import {buildReportContext} from '../src/services/reportContext';
import {InterviewAssistantWorker} from '../src/services/interviewAssistantWorker';
import {startedCase} from './support/workspaceFixtures';
import {FakeInterviewProvider} from './support/workspaceFixtures';
import {operator} from './support/preparationFixtures';

let h:Awaited<ReturnType<typeof createDiagnosisHarness>>,hearing:DiagnosisHearingRepo,ip=1;const staff:Actor={kind:'STAFF',userId:'phase3@test'};const q=SURVEY_QUESTIONS.find(x=>x.answer_type==='SINGLE_SELECT'&&x.options_json?.length)!;
before(async()=>{h=await createDiagnosisHarness();hearing=new DiagnosisHearingRepo(h.pool);});after(async()=>h.close());
async function make(){const r=await fetch(h.url+'/api/it-management-diagnosis/cases',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://www.atlib.jp','X-Forwarded-For':'192.0.2.'+(ip++)},body:JSON.stringify({companyName:'P3',contactName:'T',email:randomUUID()+'@test.invalid',phone:'0'})});assert.equal(r.status,201);return await r.json() as {id:string;access_token:string};}
async function record(caseId:string,question=q){const x=await hearing.save(caseId,staff,{questionCode:question.question_code,questionVersion:question.version,expectedVersion:null,answer:question.options_json![0]!,statement:'old',unknownNote:''});const rev=(await hearing.revisions(caseId,question.question_code,staff))[0];return {recordId:x.id,rev};}
async function execution(caseId:string){const id=randomUUID();await h.pool.query(`INSERT INTO ai_executions(id,diagnosis_case_id,process_type,status,provider,model,prompt_version,policy_version,input_snapshot_json,requested_by_user_id) VALUES($1,$2,'POST_DIAGNOSIS_STRUCTURER','SUCCEEDED','test','test','p','p','{}',$3)`,[id,caseId,'test']);return id;}
async function client<T>(f:(c:any)=>Promise<T>){const c=await h.pool.connect();try{return await f(c);}finally{c.release();}}
async function queuedSuggestion(caseId:string,recordId:string,revisionId:string){const provider=new FakeInterviewProvider();provider.run=async context=>({suggestions:[{suggestion_type:'FOLLOW_UP',text:'confirm hearing',purpose:'confirm',related_theme_id:context.themes[0]?.id??null,source_refs:[{source_ref_type:'HEARING_RECORD',source_ref_id:recordId,source_revision_id:revisionId,relation:'RELATED'}]}]});const worker=new InterviewAssistantWorker(h.preparation,h.workspace,provider);const job=await h.workspace.enqueue(caseId,operator,'fake','test');await worker.tick();return job.execution_id;}

test('1 originals: web response and hearing record are separate',async()=>{const c=await make(),customer:Actor={kind:'CUSTOMER',token:c.access_token};await h.repo.startSurvey(c.id,customer);await h.repo.submitResponse(c.id,q.question_code,q.version,q.options_json![0]!,customer);await record(c.id);assert.equal((await h.pool.query('SELECT * FROM survey_responses WHERE diagnosis_case_id=$1',[c.id])).rows.length,1);assert.equal((await h.pool.query('SELECT * FROM diagnosis_hearing_records WHERE diagnosis_case_id=$1',[c.id])).rows.length,1);});
test('2 initial revision persists through enqueue, worker and proposal storage',async()=>{const c=await startedCase(h),x=await record(c.id),job=await queuedSuggestion(c.id,x.recordId,x.rev.id);const p=(await h.pool.query('SELECT id FROM ai_proposals WHERE ai_execution_id=$1',[job])).rows[0];assert.equal((await h.pool.query('SELECT source_revision_id FROM ai_proposal_sources WHERE ai_proposal_id=$1',[p.id])).rows[0].source_revision_id,x.rev.id);});
test('3 corrected record retains old revision JSON',async()=>{const c=await make(),x=await record(c.id);await hearing.save(c.id,staff,{questionCode:q.question_code,questionVersion:q.version,expectedVersion:1,answer:q.options_json![0]!,statement:'new',unknownNote:'',reason:'fix'});assert.equal((await h.pool.query('SELECT current_json->>\'statement\' AS s FROM diagnosis_hearing_record_revisions WHERE id=$1',[x.rev.id])).rows[0].s,'old');});
test('4 enqueue snapshots remain pinned while a later enqueue uses corrected revision',async()=>{const c=await startedCase(h),x=await record(c.id),before=await h.workspace.enqueue(c.id,operator,'fake','test');await hearing.save(c.id,staff,{questionCode:q.question_code,questionVersion:q.version,expectedVersion:1,answer:q.options_json![0]!,statement:'new',unknownNote:'',reason:'fix'});const after=await h.workspace.enqueue(c.id,operator,'fake','test').catch(async()=>{await h.pool.query(`UPDATE ai_executions SET status='FAILED' WHERE id=$1`,[before.execution_id]);return h.workspace.enqueue(c.id,operator,'fake','test');});const a=(await h.pool.query('SELECT input_snapshot_json FROM ai_executions WHERE id=$1',[after.execution_id])).rows[0].input_snapshot_json,b=(await h.pool.query('SELECT input_snapshot_json FROM ai_executions WHERE id=$1',[before.execution_id])).rows[0].input_snapshot_json;assert.equal(b.hearing_records[0].revision_id,x.rev.id);assert.equal(b.hearing_records[0].statement,'old');assert.notEqual(a.hearing_records[0].revision_id,x.rev.id);assert.equal(a.hearing_records[0].statement,'new');await h.pool.query(`UPDATE ai_executions SET status='FAILED' WHERE id=$1`,[after.execution_id]);});
test('5 snapshot rejects absent revision',()=>{assert.throws(()=>validateInterviewOutput({suggestions:[{suggestion_type:'FOLLOW_UP',text:'a',purpose:'b',related_theme_id:null,source_refs:[{source_ref_type:'HEARING_RECORD',source_ref_id:randomUUID(),source_revision_id:randomUUID(),relation:'RELATED'}]}]},new Set(),new Set()));});
test('6 DB rejects foreign-case hearing revision',async()=>{const a=await make(),b=await make(),x=await record(a.id),e=await execution(b.id),p=randomUUID();await h.pool.query(`INSERT INTO ai_proposals(id,diagnosis_case_id,ai_execution_id,proposal_type,title,content_json,display_order) VALUES($1,$2,$3,'OBSERVATION','t','{}',1)`,[p,b.id,e]);await assert.rejects(h.pool.query(`INSERT INTO ai_proposal_sources(ai_proposal_id,diagnosis_case_id,source_ref_type,source_ref_id,source_revision_id,relation) VALUES($1,$2,'HEARING_RECORD',$3,$4,'RELATED')`,[p,b.id,x.recordId,x.rev.id]));});
test('7 DB rejects mismatched record and revision',async()=>{const c=await make(),a=await record(c.id),q2=SURVEY_QUESTIONS.find(x=>x.question_code!==q.question_code&&x.answer_type==='SINGLE_SELECT'&&x.options_json?.length)!,b=await record(c.id,q2),e=await execution(c.id),p=randomUUID();await h.pool.query(`INSERT INTO ai_proposals(id,diagnosis_case_id,ai_execution_id,proposal_type,title,content_json,display_order) VALUES($1,$2,$3,'OBSERVATION','t','{}',1)`,[p,c.id,e]);await assert.rejects(h.pool.query(`INSERT INTO ai_proposal_sources(ai_proposal_id,diagnosis_case_id,source_ref_type,source_ref_id,source_revision_id,relation) VALUES($1,$2,'HEARING_RECORD',$3,$4,'RELATED')`,[p,c.id,a.recordId,b.rev.id]));});
test('8 schema rejects hearing revision omission',()=>assert.throws(()=>validateStructurerOutput({insight_candidates:[{semantic_type:'OBSERVATION',title:'a',content:'b',unknown_type:null,diagnosis_theme_id:null,area_tag:null,improvement_lens:null,source_refs:[{source_ref_type:'HEARING_RECORD',source_ref_id:randomUUID(),relation:'RELATED'}]}],assessment_confirmation_items:[]},new Set(),new Set())));
test('9 legacy source kinds remain revisionless',()=>{const id=randomUUID();assert.doesNotThrow(()=>validateStructurerOutput({insight_candidates:['SURVEY_RESPONSE','SOURCE_RECORD'].map(source_ref_type=>({semantic_type:'OBSERVATION',title:'a',content:'b',unknown_type:null,diagnosis_theme_id:null,area_tag:null,improvement_lens:null,source_refs:[{source_ref_type,source_ref_id:id,relation:'RELATED'}]})),assessment_confirmation_items:[]},new Set(['SURVEY_RESPONSE:'+id,'SOURCE_RECORD:'+id]),new Set()));});
test('10 worker proposal requires an explicit Human Review command to persist a revision',async()=>{const c=await startedCase(h),x=await record(c.id);await queuedSuggestion(c.id,x.recordId,x.rev.id);assert.equal((await h.pool.query("SELECT * FROM diagnosis_insights WHERE diagnosis_case_id=$1 AND review_status='HUMAN_APPROVED'",[c.id])).rows.length,0);await h.workspace.transition(c.id,operator,'FINISH',(await h.workspace.read(c.id,operator)).version);const made=await h.review.createInsight(c.id,operator,{semantic_type:'OBSERVATION',title:'human reviewed',content:'hearing reference retained',unknown_type:null,diagnosis_theme_id:null,area_tag:null,improvement_lens:null,source_refs:[{source_ref_type:'HEARING_RECORD',source_ref_id:x.recordId,source_revision_id:x.rev.id,relation:'RELATED'}]});assert.equal((await h.pool.query('SELECT source_revision_id FROM insight_sources WHERE diagnosis_insight_id=$1',[made.id])).rows[0].source_revision_id,x.rev.id);const read=await h.review.read(c.id,operator);assert.equal((read.approved_insights[0].source_refs as any[])[0].source_revision_id,x.rev.id);});
test('11 Report Context does not connect different revisions but connects the same revision',async()=>{const c=await startedCase(h),x=await record(c.id);await hearing.save(c.id,staff,{questionCode:q.question_code,questionVersion:q.version,expectedVersion:1,answer:q.options_json![0]!,statement:'new',unknownNote:'',reason:'fix'});const rev2=(await hearing.revisions(c.id,q.question_code,staff))[1],oldObservation=randomUUID(),newHypothesis=randomUUID(),sameObservation=randomUUID(),sameHypothesis=randomUUID();for(const [i,type,r] of [[oldObservation,'OBSERVATION',x.rev.id],[newHypothesis,'HYPOTHESIS',rev2.id],[sameObservation,'OBSERVATION',rev2.id],[sameHypothesis,'HYPOTHESIS',rev2.id]] as const){await h.pool.query(`INSERT INTO diagnosis_insights(id,diagnosis_case_id,semantic_type,title,content,review_status,created_by,created_by_user_id) VALUES($1,$2,$3,$4,'c','HUMAN_APPROVED','HUMAN','t')`,[i,c.id,type,i]);await h.pool.query(`INSERT INTO insight_sources(diagnosis_insight_id,diagnosis_case_id,source_ref_type,source_ref_id,source_revision_id,relation) VALUES($1,$2,'HEARING_RECORD',$3,$4,'RELATED')`,[i,c.id,x.recordId,r]);}const ctx=await client(db=>buildReportContext(db,c.id)),different=ctx.insights.find(i=>i.id===newHypothesis)!,same=ctx.insights.find(i=>i.id===sameHypothesis)!;assert.equal(different.why_connection?.supporting_insight_refs.includes(oldObservation),false);assert.equal(same.why_connection?.supporting_insight_refs.includes(sameObservation),true);});
test('12 analysis separates cited and current hearing answers',async()=>{const c=await make(),x=await record(c.id);await hearing.save(c.id,staff,{questionCode:q.question_code,questionVersion:q.version,expectedVersion:1,answer:q.options_json![0]!,statement:'new',unknownNote:'',reason:'fix'});const i=randomUUID();await h.pool.query(`INSERT INTO diagnosis_insights(id,diagnosis_case_id,semantic_type,title,content,review_status,created_by,created_by_user_id) VALUES($1,$2,'OBSERVATION','t','c','HUMAN_APPROVED','HUMAN','t')`,[i,c.id]);await h.pool.query(`INSERT INTO insight_sources(diagnosis_insight_id,diagnosis_case_id,source_ref_type,source_ref_id,source_revision_id,relation) VALUES($1,$2,'HEARING_RECORD',$3,$4,'RELATED')`,[i,c.id,x.recordId,x.rev.id]);const view=await client(db=>managementAnalysisReadModel(db,c.id)),s=(view.items[0] as any).sources[0];assert.equal(s.referenced_answer.statement,'old');assert.equal(s.current_answer.statement,'new');});
