import {test,expect} from '@playwright/test';
import {createDiagnosisHarness} from './support/diagnosisHarness';
import {feedbackCase} from './support/assessmentFixtures';
import {operator} from './support/preparationFixtures';
let h:Awaited<ReturnType<typeof createDiagnosisHarness>>;
test.beforeAll(async()=>{h=await createDiagnosisHarness();});test.afterAll(async()=>{await h?.close();});test.beforeEach(async({context})=>{await context.addCookies([{name:'staff_session',value:h.staffCookie.slice('staff_session='.length),url:h.url,httpOnly:true,sameSite:'Lax'}]);});

test('Assessment受注: 保留guard→受注→snapshot→JSON引渡し→Human Close',async({page},info)=>{
 const c=await feedbackCase(h),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${h.url}/admin/it-management-diagnosis-report.html?id=${c.id}`);await page.locator('#tab-assessment').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：未提案');await expect(page.locator('#assessment-close')).toBeDisabled();await expect(page.locator('#company')).toHaveText('ABC株式会社様');
 page.once('dialog',d=>d.accept());await page.locator('#assessment-propose').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：提案済み');page.once('dialog',d=>d.accept());await page.locator('#assessment-pending').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：回答保留');await expect(page.locator('#assessment-close')).toBeDisabled();await expect(page.locator('#assessment-generate')).toBeDisabled();await expect(page.locator('#assessment-next')).toContainText('回答待ち');
 page.once('dialog',d=>d.accept());await page.locator('#assessment-accept').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：受注');await expect(page.locator('#assessment-close')).toBeDisabled();await page.locator('#assessment-generate').click();await expect(page.locator('#handoff-status')).toHaveText('引継ぎ情報 第1版 / 引渡し可能');await expect(page.locator('#assessment-close')).toBeDisabled();await expect(page.locator('#handoff-future')).toContainText('SURVEY_STATED');await expect(page.locator('#handoff-future')).toContainText('v1');await expect(page.locator('#handoff-hash')).toContainText('SHA-256：');await expect(page.locator('#handoff-insights')).toContainText('UNKNOWN / HUMAN_APPROVED');await expect(page.locator('#handoff-insights')).toContainText('HYPOTHESIS / HUMAN_APPROVED');await expect(page.locator('#handoff-items')).toContainText('OPEN');
 await page.locator('#handoff-insights summary').first().click();await expect(page.locator('#handoff-insights')).toContainText('SOURCE_RECORD');await expect(page.locator('#handoff-snapshot')).toContainText('schema_version');const download=page.waitForEvent('download');await page.locator('#assessment-download').click();expect((await download).suggestedFilename()).toBe('assessment-handoff-v1.json');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();await page.screenshot({path:info.outputPath('assessment-ready.png'),fullPage:true});
 const frozen=(await h.assessment.read(c.id,operator)).latest_handoff!;page.once('dialog',d=>d.accept());await page.locator('#assessment-transfer').click();await expect(page.locator('#handoff-status')).toHaveText('引継ぎ情報 第1版 / 引渡し済み');await expect(page.locator('#case-status')).toContainText('FEEDBACK_COMPLETED');await expect(page.locator('#assessment-close')).toBeEnabled();
 page.once('dialog',d=>d.accept());await page.locator('#assessment-close').click();await expect(page.locator('#case-status')).toContainText('CLOSED');await expect(page.locator('#close-metadata')).toContainText('operator@atlib.jp');await expect(page.locator('#assessment-close')).toBeDisabled();await expect(page.locator('#assessment-audit')).toContainText('CloseDiagnosisCase');await expect(page.locator('#assessment-audit')).toContainText('operator@atlib.jp');await expect(page.locator('#assessment-transitions')).toContainText('CloseDiagnosisCase');const result=await h.assessment.read(c.id,operator);expect(result.latest_handoff!.snapshot_json).toEqual(frozen.snapshot_json);expect(result.latest_handoff!.snapshot_hash).toBe(frozen.snapshot_hash);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('assessment-closed.png'),fullPage:true});
 await page.goto(`${h.url}/admin/it-management-diagnosis.html`);await page.locator('#status-filter').selectOption('CLOSED');await expect(page.getByText('ABC株式会社様').first()).toBeVisible();await page.goto(`${h.url}/it-management-diagnosis.html#case=${c.id}&token=${c.access_token}`);await expect(page.locator('#survey-success')).toBeVisible();
});

test('Assessment辞退: Humanが記録しHandoffなしでClose',async({page},info)=>{
 const c=await feedbackCase(h);await page.goto(`${h.url}/admin/it-management-diagnosis-report.html?id=${c.id}`);await page.locator('#tab-assessment').click();await expect(page.locator('#assessment-propose')).toBeEnabled();page.once('dialog',d=>d.accept());await page.locator('#assessment-propose').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：提案済み');await page.locator('#assessment-reason').fill('今回は見送るとの回答');page.once('dialog',d=>d.accept());await page.locator('#assessment-decline').click();await expect(page.locator('#assessment-status')).toHaveText('設計Assessment状況：辞退');await expect(page.locator('#assessment-generate')).toBeDisabled();await expect(page.locator('#assessment-close')).toBeEnabled();page.once('dialog',d=>d.accept());await page.locator('#assessment-close').click();await expect(page.locator('#case-status')).toContainText('CLOSED');expect((await h.assessment.read(c.id,operator)).handoffs).toHaveLength(0);await page.screenshot({path:info.outputPath('assessment-declined-closed.png'),fullPage:true});
});

test('Handoff再生成: 新versionがREADYなら旧版transfer済みでもClose不可',async({page})=>{
 const c=await feedbackCase(h);for(const action of ['propose','accept'] as const)await h.assessment.lifecycle(c.id,operator,action,(await h.assessment.read(c.id,operator)).version,'');await h.assessment.generate(c.id,operator,(await h.assessment.read(c.id,operator)).version,'');let d=await h.assessment.read(c.id,operator);await h.assessment.transfer(c.id,operator,d.latest_handoff!.id,d.version,'');const old=d.latest_handoff!;
 await page.goto(`${h.url}/admin/it-management-diagnosis-report.html?id=${c.id}`);await page.locator('#tab-assessment').click();await expect(page.locator('#assessment-close')).toBeEnabled();await page.locator('#assessment-generate').click();await expect(page.locator('#handoff-status')).toHaveText('引継ぎ情報 第2版 / 引渡し可能');await expect(page.locator('#assessment-close')).toBeDisabled();await page.locator('#handoff-version').selectOption(old.id);await expect(page.locator('#handoff-status')).toHaveText('引継ぎ情報 第1版 / 引渡し済み');await expect(page.locator('#assessment-transfer')).toBeDisabled();await expect(page.locator('#assessment-close')).toBeDisabled();d=await h.assessment.read(c.id,operator);expect(d.handoffs[1]!.snapshot_json).toEqual(old.snapshot_json);
});
