import assert from 'node:assert/strict';
import {test} from 'node:test';
import {contentHash,type StoredReport} from '../src/domain/diagnosisReport';
import {DiagnosisReportPdfService} from '../src/services/diagnosisReportPdfService';
import {reportPdfObjectKey,reportPdfSha256} from '../src/services/diagnosisReportPdfArtifact';

const caseId='11111111-1111-4111-8111-111111111111',reportId='22222222-2222-4222-8222-222222222222';
const content:StoredReport={sections:[{section_key:'FUTURE',title:'t',blocks:[{block_id:'b',section:'FUTURE',block_type:'FUTURE',text:'approved',insight_refs:[],assessment_refs:[]}]}]};
const source={id:reportId,diagnosis_case_id:caseId,version:1,status:'APPROVED',content_json:content,snapshot_json:{organization_display_name:'o',provider_display_name:'p',content_hash:contentHash(content),approved_at:'2026-01-01T00:00:00.000Z',approved_by:'staff',report_version:1}};
const identity={caseId,reportId,version:1},pdf=Buffer.from('%PDF-1.4\nservice'),stored={objectKey:reportPdfObjectKey(identity),sha256:reportPdfSha256(pdf),sizeBytes:pdf.length};
function service(options:{status?:string;existing?:boolean;badHash?:boolean;renderFails?:boolean;acquired?:boolean;existingError?:string;downloadError?:string}={}){let failed=0,ready=0,puts=0;const artifact={report_id:reportId,diagnosis_case_id:caseId,report_version:1,status:options.status??'PENDING',object_key:options.status==='READY'?stored.objectKey:null,pdf_sha256:options.status==='READY'?stored.sha256:null,pdf_size_bytes:options.status==='READY'?stored.sizeBytes:null,error_code:null,source_content_hash:options.badHash?'a'.repeat(64):source.snapshot_json.content_hash};const repo={claim:async()=>({artifact,acquired:options.acquired??artifact.status==='PENDING',generationToken:'33333333-3333-4333-8333-333333333333'}),ready:async()=>{ready++;return {...artifact,status:'READY'}},failed:async()=>{failed++},read:async()=>artifact};const store={readExisting:async()=>{if(options.existingError)throw new Error(options.existingError);return options.existing?{pdf,stored}:null},putImmutable:async()=>{puts++;return stored},getVerified:async()=>{if(options.downloadError)throw new Error(options.downloadError);return pdf}};const pool={query:async(_sql:string,params:string[])=>({rows:params[0]===reportId&&params[1]===caseId?[source]:[]})};return {svc:new DiagnosisReportPdfService(pool as never,repo as never,store as never,async()=>{if(options.renderFails)throw new Error('PDF_RENDER_FAILED');return pdf}),counts:()=>({ready,failed,puts})};}
test('service generates approved PDF, reuses READY and rejects source hash mismatch',async()=>{const a=service();assert.equal((await a.svc.generate(caseId,reportId)).status,'READY');assert.deepEqual(a.counts(),{ready:1,failed:0,puts:1});const b=service({status:'READY'});assert.equal((await b.svc.generate(caseId,reportId)).status,'READY');const c=service({status:'READY',badHash:true});await assert.rejects(c.svc.generate(caseId,reportId),/PDF_ARTIFACT_SOURCE_HASH_MISMATCH/);});
test('service rejects wrong case, bad snapshot, failed GCS and verifies download hash',async()=>{const a=service();await assert.rejects(a.svc.generate('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',reportId),/REPORT_NOT_FOUND/);const b=service({renderFails:true});await assert.rejects(b.svc.generate(caseId,reportId),/PDF_RENDER_FAILED/);assert.equal(b.counts().failed,1);const c=service({status:'READY'});assert.deepEqual(await c.svc.download(caseId,reportId),pdf);});
test('service recovers an uploaded immutable object and rejects incompatible object metadata',async()=>{const recovered=service({existing:true});assert.equal((await recovered.svc.generate(caseId,reportId)).status,'READY');assert.equal(recovered.counts().puts,0);const mismatch=service({existingError:'DIAGNOSIS_REPORT_PDF_GCS_SOURCE_HASH_MISMATCH'});await assert.rejects(mismatch.svc.generate(caseId,reportId),/DIAGNOSIS_REPORT_PDF_GCS_SOURCE_HASH_MISMATCH/);assert.equal(mismatch.counts().failed,1);});
test('service does not render while another valid lease owns PENDING and rejects download hash failures',async()=>{const pending=service({acquired:false});assert.equal((await pending.svc.generate(caseId,reportId)).status,'PENDING');assert.equal(pending.counts().puts,0);const corrupted=service({status:'READY',downloadError:'DIAGNOSIS_REPORT_PDF_HASH_MISMATCH'});await assert.rejects(corrupted.svc.download(caseId,reportId),/DIAGNOSIS_REPORT_PDF_HASH_MISMATCH/);});
