import {test,expect,type Page} from '@playwright/test';
import {createDiagnosisHarness} from './support/diagnosisHarness';
import {FakePostDiagnosisProvider,structurerOutput} from './support/reviewFixtures';
import {feedbackCase} from './support/assessmentFixtures';
import {operator} from './support/preparationFixtures';
import {SURVEY_QUESTIONS} from '../src/domain/itManagementDiagnosis';
let h:Awaited<ReturnType<typeof createDiagnosisHarness>>;const provider=new FakePostDiagnosisProvider();
test.beforeAll(async()=>{provider.run=async c=>{const out=structurerOutput(c);const names=['取得した回答についての観察','更新担当者の未確認事項','共有方法の仮説','目指す姿との差の候補','役割分担に関する理由の仮説','共有方法を整える選択肢','資料等の確認候補'];out.insight_candidates.forEach((i,n)=>i.title=names[n]!);return out;};h=await createDiagnosisHarness(undefined,undefined,undefined,provider);});
test.afterAll(async()=>{await h?.close();});
test.beforeEach(async({context,page})=>{page.setDefaultTimeout(15000);await context.addCookies([{name:'staff_session',value:h.staffCookie.slice('staff_session='.length),url:h.url,httpOnly:true,sameSite:'Lax'}]);});
async function confirm(page:Page,selector:string){page.once('dialog',d=>d.accept());await page.locator(selector).click();}
async function decision(page:Page,route:string){await page.locator('#tab-assessment').click();await page.locator('#decision-route').selectOption(route);await page.locator('#decision-material').fill('経営者と確認した次の進め方');await page.locator('#decision-next').fill('人が次回の具体的な行動を確認する');await confirm(page,'#decision-save');}
async function feedback(page:Page){await page.locator('#manual').click();await expect(page.locator('#report-status')).toContainText('担当者確認待ち');await confirm(page,'#approve');await expect(page.locator('#case-status')).toContainText('承認済み');await confirm(page,'#deliver');await page.locator('#tab-feedback').click();await page.locator('#start-feedback').click();await page.locator('#feedback-content').fill('今も分からないことがあるので次の進め方を相談したい');await page.locator('#save-feedback').click();await expect(page.locator('#feedback-sources')).toContainText('次の進め方を相談');await confirm(page,'#complete-feedback');await expect(page.locator('#case-status')).toHaveText('進行状況：経営フィードバック完了');}
async function auditScreen(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();expect(await page.locator('body').innerText()).not.toMatch(/\bFACT\b|\bUNKNOWN\b|\bHYPOTHESIS\b|GAP_CANDIDATE|KAIZEN_DIRECTION|semantic_type|SourceRecord|Human Review|\bContext\b|\bEvidence\b|\bPlanItem\b|\bsnapshot\b|\bAudit\b|CaseTransition/);}

test('SL-A6 A/C–K: sales intake to Human decision and independent Assessment handoff, entirely through browser',async({page},info)=>{
 test.setTimeout(90000);const before=(await h.pool.query('SELECT id FROM diagnosis_cases')).rowCount;
 await page.goto(h.url+'/admin/it-management-diagnosis.html');await page.getByRole('link',{name:'営業で伺った内容を登録する'}).click();
 await page.locator('#company-name').fill('営業一貫テスト');await page.locator('#contact-name').fill('田中');await page.locator('#email').fill('launch@example.test');await page.locator('#customer-statements').fill('売上を伸ばしたいと伺った');await page.locator('#unknowns').fill('更新担当者はまだ分からない');await page.locator('#salesperson-notes').fill('役割の整理が必要かもしれない');
 await page.getByText('既に伺った回答を記録する（任意）',{exact:true}).click();await page.locator('[data-code="Q01_FUTURE"] input').first().check();await page.locator('[data-code="Q04_IT_VISIBILITY"]').getByLabel('分からない',{exact:true}).check();await page.locator('#save').click();await expect(page.locator('#consent')).toBeVisible();expect((await h.pool.query('SELECT id FROM diagnosis_cases')).rowCount).toBe(before);await auditScreen(page);
 const intakeId=new URL(page.url()).searchParams.get('id')!;await page.reload();await expect(page.locator('#unknowns')).toHaveValue('更新担当者はまだ分からない');await page.locator('#consent-customer').fill('田中');await page.locator('#customer-agreed').check();await page.locator('#start').click();await expect(page.locator('#survey-questions')).toBeVisible();const id=new URL(page.url()).searchParams.get('id')!;
 expect((await h.pool.query('SELECT id FROM diagnosis_cases')).rowCount).toBe(before!+1);
 await page.goto(h.url+'/admin/it-management-diagnosis-detail.html?id='+id);await page.getByRole('link',{name:'足りない回答を確認する'}).click();await expect(page.locator('[data-question-code="Q04_IT_VISIBILITY"]')).toBeHidden();
 for(const q of SURVEY_QUESTIONS.filter(q=>q.is_required&&!['Q01_FUTURE','Q04_IT_VISIBILITY'].includes(q.question_code)))await page.locator(`[data-question-code="${q.question_code}"]`).getByLabel('分からない',{exact:true}).check();await page.getByRole('button',{name:'途中保存する',exact:true}).click();await expect(page.locator('#save-status')).toContainText('回答を保存しました');await page.reload();await page.getByRole('button',{name:'回答を完了する',exact:true}).click();await expect(page.locator('#survey-success')).toBeVisible();
 await page.goto(h.url+'/admin/it-management-diagnosis-detail.html?id='+id);await expect(page.locator('#reuse-known')).toContainText('売上を伸ばしたい');await expect(page.locator('#reuse-unknown')).toContainText('更新担当者はまだ分からない');await expect(page.locator('#reuse-hypotheses')).toContainText('役割の整理');await auditScreen(page);
 const intake=(await h.pool.query('SELECT * FROM sales_conversation_intakes WHERE id=$1',[intakeId])).rows[0];expect(intake.diagnosis_case_id).toBe(id);expect((await h.pool.query('SELECT intake_origin_id FROM survey_responses WHERE diagnosis_case_id=$1 AND intake_origin_id IS NOT NULL',[id])).rows.length).toBe(2);
 await page.locator('#reuse-next a').click();await page.locator('#start').click();await page.locator('#theme-title').fill('役割の確認');await page.locator('#theme-relation').fill('目指す会社の姿に必要な役割を確認する');await page.locator('#save-theme').click();await expect(page.locator('#themes')).toContainText('役割の確認');
 await page.locator('#reuse-candidates [data-reuse-key="intake:unknowns:0"]').getByRole('button',{name:'今回確認する',exact:true}).click();await page.locator('#reuse-question').fill('更新担当者を把握していますか');await page.locator('#reuse-purpose').fill('不明な担当者を確認する');await page.getByRole('button',{name:'今回確認する内容に追加',exact:true}).click();await expect(page.locator('#reuse-selected')).toContainText('更新担当者を把握');await confirm(page,'#confirm');await page.locator('#workspace-link').click();await page.locator('#start').click();
 await page.locator('#reuse-selected').getByRole('button',{name:'この内容を確認して記録する'}).click();await expect(page.locator('#statement-content')).toHaveValue('');await page.locator('#statement-content').fill('更新担当者は今も分かりません');await page.getByRole('button',{name:'顧客発言を保存',exact:true}).click();await expect(page.locator('#reuse-unknown')).toContainText('更新担当者はまだ分からない');await auditScreen(page);await confirm(page,'#finish');await page.locator('#review-link').click();
 await page.locator('#run-ai').click();await expect(page.locator('#executions')).toContainText('整理完了');expect((await h.review.read(id,operator)).approved_insights).toHaveLength(0);const model=await h.review.read(id,operator);const card=(type:string)=>page.locator(`[data-proposal-id="${model.proposals.find(p=>p.proposal_type===type).id}"]`);
 await expect(page.locator('#analysis-why')).toContainText('理由についての仮説');await expect(page.locator('#analysis-lens > section')).toHaveCount(1);await auditScreen(page);
 await card('OBSERVATION').getByRole('button',{name:'編集して採用する',exact:true}).click();await page.locator('#insight-content').fill('更新担当者が分からないという顧客発言を取得した');await page.locator('#save-insight').click();await expect(page.locator('#approved')).toContainText('顧客発言を取得した');
 await card('KAIZEN_DIRECTION').getByRole('button',{name:'採用する',exact:true}).click();await expect(page.locator('#approved')).toContainText('共有方法を整える選択肢');await card('GAP_CANDIDATE').getByRole('button',{name:'まだ分かっていないこととして残す',exact:true}).click();await page.locator('#convert-type').selectOption('UNRESOLVED');await page.locator('#convert-reason').fill('判断する情報がまだ足りない');await page.getByRole('button',{name:'まだ分かっていないこととして保存',exact:true}).click();await expect(page.locator('#approved')).toContainText('確認したがまだ分からない');await card('ROOT_CAUSE_HYPOTHESIS').getByRole('button',{name:'採用しない',exact:true}).click();await expect(card('ROOT_CAUSE_HYPOTHESIS')).toContainText('不採用');
 await page.locator('#leave-unreviewed').check();await confirm(page,'#complete');await page.locator('#report-link').click();await feedback(page);
 await page.locator('#tab-report').click();await expect(page.locator('#report-sections > section > h2')).toHaveText(['1. 目指している会社の姿','2. 今、確認できていること','3. まだ分かっていないこと','4. ITで良くできそうなこと','5. 次に確認・判断すること']);await auditScreen(page);
 const reports=(await h.report.read(id,operator)).reports;expect(reports[0]!.context_json.insights.every(i=>model.proposals.every(p=>p.id!==i.id))).toBe(true);expect(reports[0]!.context_json.insights).toHaveLength(3);
 await decision(page,'DESIGN_ASSESSMENT');await expect(page.locator('#case-status')).toHaveText('進行状況：完了');let state=await h.assessment.read(id,operator);expect(state.assessment_status).toBe('NOT_PROPOSED');expect(state.handoffs).toHaveLength(0);await auditScreen(page);
 await confirm(page,'#assessment-propose');await expect(page.locator('#assessment-status')).toContainText('提案済み');await confirm(page,'#assessment-pending');await expect(page.locator('#assessment-status')).toContainText('回答保留');await confirm(page,'#assessment-accept');await expect(page.locator('#assessment-status')).toContainText('受注');await page.locator('#assessment-generate').click();await expect(page.locator('#handoff-status')).toContainText('引渡し可能');const frozen=(await h.assessment.read(id,operator)).latest_handoff!;await confirm(page,'#assessment-transfer');await expect(page.locator('#handoff-status')).toContainText('引渡し済み');state=await h.assessment.read(id,operator);expect(state.latest_handoff!.snapshot_json).toEqual(frozen.snapshot_json);expect(state.latest_handoff!.snapshot_json.insights.every(i=>i.source_refs.length>0)).toBe(true);expect(state.diagnosis_status).toBe('CLOSED');await auditScreen(page);await page.screenshot({path:info.outputPath('sales-launch-completed.png'),fullPage:true});
});

test('SL-A6 I/K: focused confirmation -> raw speech -> review -> feedback -> Human Re-Decision in browser',async({page},info)=>{
 test.setTimeout(90000);const c=await feedbackCase(h,{decision:false});const oldInsights=(await h.review.read(c.id,operator)).approved_insights;
 await page.goto(h.url+'/admin/it-management-diagnosis-report.html?id='+c.id);await decision(page,'FOCUSED_CONFIRMATION');await expect(page.locator('#focused-workspace')).toBeVisible();const first=(await h.feedbackDecision.read(c.id,operator)).latest!;await page.locator('#focused-workspace').click();
 await expect(page.locator('#reuse-selected')).toBeVisible();await page.locator('#reuse-selected').getByRole('button',{name:'この内容を確認して記録する'}).first().click();await page.locator('#statement-content').fill('追加確認しても担当者の範囲はまだ分かりません');await page.getByRole('button',{name:'顧客発言を保存',exact:true}).click();await expect(page.locator('#reuse-known')).toContainText('追加確認しても');expect((await h.review.read(c.id,operator)).approved_insights).toEqual(oldInsights);await confirm(page,'#finish');await page.locator('#review-link').click();await expect(page.locator('#raw-sources')).toContainText('追加確認しても');await confirm(page,'#complete');await page.locator('#report-link').click();await feedback(page);await decision(page,'STOP_HOLD');await expect(page.locator('#case-status')).toHaveText('進行状況：完了');
 const after=await h.feedbackDecision.read(c.id,operator);expect(after.history).toHaveLength(2);expect(after.history[1]).toEqual(first);expect(after.latest!.supersedes_decision_id).toBe(first.id);expect((await h.assessment.read(c.id,operator)).assessment_status).toBe('NOT_PROPOSED');await page.getByText('次の進め方の判断履歴',{exact:true}).click();await expect(page.locator('#decision-history')).toContainText('operator@atlib.jp');await auditScreen(page);await page.screenshot({path:info.outputPath('human-redecision-history.png'),fullPage:true});
});
test('SL-A6 K: DIRECT_ACT completes without an Assessment proposal through Human UI',async({page})=>{const c=await feedbackCase(h,{decision:false});await page.goto(h.url+'/admin/it-management-diagnosis-report.html?id='+c.id);await decision(page,'DIRECT_ACT');await expect(page.locator('#case-status')).toHaveText('進行状況：完了');await expect(page.locator('#assessment-propose')).toBeDisabled();expect((await h.assessment.read(c.id,operator)).assessment_status).toBe('NOT_PROPOSED');await page.reload();await expect(page.locator('#decision-guidance')).toContainText('無料診断は完了');await auditScreen(page);});
