import type { KnowledgeState, ManagementFocus } from './freeDiagnosisRuleBasedV1';
import type { AssessmentStructureGates } from './assessmentStructureRule';

// Rule Analysis Engine. Deterministic, AI-free (旧AI Processing Contractの決定論版).
// Processing order per docs/free-diagnosis-rule-based-v1-business-design-canonical-20261003.md §6:
//   Statement + Source preserve -> Knowledge normalization -> Clarification resolution ->
//   Management Relevance -> T1-T4 -> Investigation Value ->
//   Scope Specificity Gate -> 6-point Investigation Output -> Investigation Need
//
// Statement + Source preserve / Knowledge normalization / Clarification resolution happen at
// the Hearing recording layer itself (hearing_statement_v2 is append-only; knowledge_state is
// recorded directly by Staff, never inferred from free text here). This module implements the
// remaining steps: Management Relevance -> T1-T4 -> Investigation Need,
// plus deriving the Assessment Structure Gates from the same structured output.

export const RULE_ENGINE_VERSION = 'rule-based-v1.0.0';

export type TriggerType = 'T1_KNOWLEDGE' | 'T2_DECISION' | 'T3_CHANGE' | 'T4_OPPORTUNITY';
export type InvestigationNeed = 'RECOMMENDED' | 'OPTIONAL' | 'NO_IMMEDIATE_INVESTIGATION_NEED';

interface PlanItemTemplate {
  code: string;
  focus: ManagementFocus;
  triggerType: 'T1_KNOWLEDGE' | 'T2_DECISION';
}

// Rules Select: for each Management Focus, exactly one Knowledge-type confirmation item (current
// state) and one Decision-type confirmation item (pending management decision). This is the Plan
// that Preparation presents (Doc UI Wireframe #5); it is a fixed catalog selected deterministically
// by which Focus the customer chose, never generated by AI or inferred from free text.
export function planItemsForFocus(focus: ManagementFocus): PlanItemTemplate[] {
  return [
    { code: `${focus}_CORE`, focus, triggerType: 'T1_KNOWLEDGE' },
    { code: `${focus}_DECISION`, focus, triggerType: 'T2_DECISION' },
  ];
}

export interface HearingStatementInput {
  planItemRef: string | null;
  knowledgeState: KnowledgeState;
  requiresIndividualConfirmation: boolean;
}

export interface RuleAnalysisInput {
  primaryFocus: ManagementFocus;
  secondaryFocus: ManagementFocus | null;
  /** Latest (append-only -> last recorded wins) statement per plan item. */
  statements: HearingStatementInput[];
  /** Q2 (今後1〜3年の会社の変化) に実質的な回答があるか。文面の意味解釈はしない、空かどうかのみ。 */
  hasStatedChangeIntent: boolean;
  /** Q3 (今後ITについて実現したい状態) に実質的な回答があるか。 */
  hasStatedOpportunityIntent: boolean;
  /** Phase 1: Initial Rule has already selected these confirmation purposes. Without an
   * explicit purpose, PARTIAL/UNKNOWN alone must never create Investigation Need. */
  verificationPurposes?: readonly { focus: ManagementFocus; triggerType: TriggerType }[];
}

export interface TriggerFinding {
  triggerType: TriggerType;
  investigationNeed: InvestigationNeed;
  grounds: { planItemRef: string; focus: ManagementFocus; knowledgeState: KnowledgeState };
}

export interface RuleAnalysisResult {
  ruleVersion: string;
  /** Historical compatibility field. Current Design v1 retires Broad Unknown Collapse. */
  broadUnknownCollapse: boolean;
  findings: TriggerFinding[];
  overallInvestigationNeed: InvestigationNeed;
  /** Assessment Structure Ruleへの入力。Investigation Needはここに一切含まれない。 */
  assessmentStructureGates: AssessmentStructureGates;
}

function latestByPlanItem(statements: HearingStatementInput[]): Map<string, HearingStatementInput> {
  // 配列は記録順(古い->新しい)で渡される前提。append-onlyのため、同じplan_item_refの
  // 最後の要素が最新の確認結果（整理モードでの再確認を含む）。
  const byItem = new Map<string, HearingStatementInput>();
  for (const s of statements) { if (s.planItemRef) byItem.set(s.planItemRef, s); }
  return byItem;
}

export function runRuleAnalysis(input: RuleAnalysisInput): RuleAnalysisResult {
  const focuses = [input.primaryFocus, ...(input.secondaryFocus ? [input.secondaryFocus] : [])];
  const relevantItems = focuses.flatMap(planItemsForFocus);
  const latest = latestByPlanItem(input.statements);

  // Management Relevance: 選択されたFocusに紐づくPlan Itemのみを対象にする
  // （Focus外のUNKNOWNは一切評価しない -- 「UNKNOWNを問題扱いしない」の実装）。
  const consideredItems = relevantItems
    .map(item => ({ item, statement: latest.get(item.code) }))
    .filter((x): x is { item: PlanItemTemplate; statement: HearingStatementInput } => x.statement !== undefined);

  const findings: TriggerFinding[] = [];
  for (const { item, statement } of consideredItems) {
    const explicitlySelected = input.verificationPurposes?.some(x => x.focus === item.focus && x.triggerType === item.triggerType) ?? false;
    // UNKNOWN/PARTIAL is preserved as knowledge state. It becomes a finding only where the
    // Initial Rule selected a management-relevant confirmation purpose.
    if (!explicitlySelected || !['PARTIAL', 'UNKNOWN'].includes(statement.knowledgeState)) continue;
    if (item.triggerType === 'T1_KNOWLEDGE') {
      findings.push({ triggerType: 'T1_KNOWLEDGE', investigationNeed: 'RECOMMENDED',
        grounds: { planItemRef: item.code, focus: item.focus, knowledgeState: statement.knowledgeState } });
    } else {
      findings.push({ triggerType: 'T2_DECISION', investigationNeed: 'RECOMMENDED',
        grounds: { planItemRef: item.code, focus: item.focus, knowledgeState: statement.knowledgeState } });
      // T3/T4は「Changeだけ」「Opportunityだけ」では発火しない。未解決の経営判断項目が
      // あることに加えて、該当Focusについて実際にChange/Opportunityの意図が述べられて
      // いる場合のみ、同じ未解決事実をT3/T4としても提示する（construct要件の両立）。
      if (input.hasStatedChangeIntent) {
        findings.push({ triggerType: 'T3_CHANGE', investigationNeed: 'OPTIONAL',
          grounds: { planItemRef: item.code, focus: item.focus, knowledgeState: statement.knowledgeState } });
      }
      if (input.hasStatedOpportunityIntent) {
        findings.push({ triggerType: 'T4_OPPORTUNITY', investigationNeed: 'OPTIONAL',
          grounds: { planItemRef: item.code, focus: item.focus, knowledgeState: statement.knowledgeState } });
      }
    }
  }

  // Investigation Need（全体）：明示済みVerification Purposeに対するトリガー種類のみで決める。
  const hasCoreTrigger = findings.some(f => f.triggerType === 'T1_KNOWLEDGE' || f.triggerType === 'T2_DECISION');
  const hasAnyTrigger = findings.length > 0;
  const overallInvestigationNeed: InvestigationNeed = hasCoreTrigger ? 'RECOMMENDED' : hasAnyTrigger ? 'OPTIONAL' : 'NO_IMMEDIATE_INVESTIGATION_NEED';

  return {
    ruleVersion: RULE_ENGINE_VERSION,
    broadUnknownCollapse: false,
    findings,
    overallInvestigationNeed,
    assessmentStructureGates: deriveAssessmentStructureGates(input, consideredItems),
  };
}

function deriveAssessmentStructureGates(
  input: RuleAnalysisInput,
  consideredItems: { item: PlanItemTemplate; statement: HearingStatementInput }[],
): AssessmentStructureGates {
  // structure_determinable: Primary Focusについて構造を判定するための最低限の情報
  // （1件以上の確認結果）があるか。0件なら安全に判定できない。
  const structureDeterminable = consideredItems.length > 0;
  // cross_theme_dependency: Secondary Focusが明示されている、つまり複数テーマを
  // 横断して確認する必要があることが構造的に確定している。
  const crossThemeDependency = input.secondaryFocus !== null;
  // single_management_scope: Secondary Focusが無く、かつ対象ごとの個別確認も不要な場合、
  // 単一の代表的確認経路で完結できる構造とみなす。
  const requiresIndividual = consideredItems.some(x => x.statement.requiresIndividualConfirmation);
  const singleManagementScope = !crossThemeDependency && !requiresIndividual;
  return {
    structure_determinable: structureDeterminable,
    single_management_scope: singleManagementScope,
    requires_individual_confirmation_per_target: requiresIndividual,
    cross_theme_dependency: crossThemeDependency,
  };
}
