import {Router} from 'express';
import {z} from 'zod';
import type {WebDevelopmentPartnerLeadRepo} from '../services/webDevelopmentPartnerLeadRepo';
import {createIpRateLimiter} from '../middleware/rateLimit';
import type {Mailer} from '../services/mailer';
import type {Config} from '../config';
import {sendSlackNotification} from '../services/slackNotifier';
const schema=z.object({companyName:z.string().min(1).max(200),contactName:z.string().min(1).max(200),email:z.string().email(),phone:z.string().max(50).optional(),consultationType:z.string().min(1).max(200),inquiry:z.string().max(2000).optional(),utmSource:z.string().max(200).optional(),utmMedium:z.string().max(200).optional(),utmCampaign:z.string().max(200).optional(),utmContent:z.string().max(200).optional(),utmTerm:z.string().max(200).optional(),ctaSource:z.string().max(100).optional(),landingUrl:z.string().max(2000).optional(),referrer:z.string().max(2000).optional(),hp:z.string().max(200).optional()});
export function createWebDevelopmentPartnerLeadRouter(repo:WebDevelopmentPartnerLeadRepo,mailer:Mailer,config:Config):Router {const r=Router();r.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','https://www.atlib.jp');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.status(204).end();next();});r.post('/',createIpRateLimiter({windowMs:3600000,maxRequests:10}),async(req,res)=>{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_PARTNER_LEAD'});if(p.data.hp)return res.status(204).end();try {const id=await repo.insert({...p.data,sourceIp:req.ip??null});const detailUrl=`${config.portalBaseUrl}/admin/web-development-partner-leads.html`;await Promise.allSettled([mailer.sendWebDevelopmentPartnerLeadNotification(config.diagnosticNotifyEmail,{company:p.data.companyName,name:p.data.contactName,email:p.data.email,phone:p.data.phone,detailUrl}),mailer.sendWebDevelopmentPartnerLeadThanks(p.data.email,{name:p.data.contactName,scheduleUrl:`https://timerex.net/s/yoshihisa.hagisaka_e611/4d232431?lead_id=${encodeURIComponent(id)}`}),sendSlackNotification(config.slack.webhookDiagnostic,`Web Development partner lead: ${p.data.companyName} / ${p.data.contactName} / ${detailUrl}`)]);return res.status(201).json({leadId:id});}catch(e){console.error('Web development partner lead insert failed',e);return res.status(500).json({error:'PARTNER_LEAD_SUBMISSION_FAILED'});}});return r;}
