import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {DiagnosisError,type Actor} from '../domain/itManagementDiagnosis';

export type ScopeClarificationDimension='TARGET_SCOPE'|'INFORMATION_LOCATION'|'MANAGEMENT_OWNER'|'EVIDENCE_ACCESS'|'INTERVIEW_SCOPE'|'SPECIAL_REQUIREMENT';
interface CaseRow{id:string;version:number;diagnosis_status:string}
export class AssessmentScopeClarificationRepo{
 constructor(private readonly pool:Pool){}
 private staff(a:Actor){if(a.kind!=='STAFF'||!a.userId)throw new DiagnosisError(403,'スタッフによる操作が必要です。');return a.userId;}
 private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private async lockRouteC(c:PoolClient,id:string,a:Actor,expectedVersion?:number){this.staff(a);const row=(await c.query<CaseRow>('SELECT id,version,diagnosis_status FROM diagnosis_cases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw new DiagnosisError(404,'案件が見つかりません。');if(expectedVersion!==undefined&&row.version!==expectedVersion)throw new DiagnosisError(409,'内容が更新されています。再読み込みしてください。');if(row.diagnosis_status!=='FEEDBACK_COMPLETED')throw new DiagnosisError(409,'Management Feedback完了後に確認してください。');const route=(await c.query<{route_code:string}>('SELECT route_code FROM management_feedback_decisions WHERE diagnosis_case_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0]?.route_code;if(route!=='DESIGN_ASSESSMENT')throw new DiagnosisError(409,'Design AssessmentがHuman Decisionされた案件だけが対象です。');return row;}
 private async audit(c:PoolClient,id:string,a:Actor,command:string,detail:unknown){await c.query('UPDATE diagnosis_cases SET version=version+1,updated_at=now() WHERE id=$1',[id]);await c.query(`INSERT INTO diagnosis_audit_logs(id,diagnosis_case_id,command,actor_type,actor_user_id,detail_json) VALUES($1,$2,$3,'STAFF',$4,$5)`,[randomUUID(),id,command,this.staff(a),JSON.stringify(detail)]);}
 async create(id:string,a:Actor,input:{expectedVersion:number;dimension:ScopeClarificationDimension;promptJa:string;reasonJa:string;sourceRefs?:unknown[]}){if(!input.promptJa?.trim()||!input.reasonJa?.trim())throw new DiagnosisError(422,'不足情報と確認理由を入力してください。');return this.tx(async c=>{await this.lockRouteC(c,id,a,input.expectedVersion);const key=randomUUID();await c.query(`INSERT INTO assessment_scope_clarifications(id,diagnosis_case_id,dimension,prompt_ja,reason_ja,source_refs_json,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7)`,[key,id,input.dimension,input.promptJa.trim(),input.reasonJa.trim(),JSON.stringify(input.sourceRefs??[]),this.staff(a)]);await this.audit(c,id,a,'CreateAssessmentScopeClarification',{clarification_id:key,dimension:input.dimension});return{id:key};});}
 async resolve(id:string,key:string,a:Actor,input:{expectedVersion:number;sourceRecordId:string}){return this.tx(async c=>{await this.lockRouteC(c,id,a,input.expectedVersion);const item=(await c.query<any>('SELECT status FROM assessment_scope_clarifications WHERE id=$1 AND diagnosis_case_id=$2 FOR UPDATE',[key,id])).rows[0];if(!item)throw new DiagnosisError(404,'確認項目が見つかりません。');if(item.status!=='OPEN')throw new DiagnosisError(409,'この確認項目は処理済みです。');const source=(await c.query<any>(`SELECT id FROM source_records WHERE id=$1 AND diagnosis_case_id=$2 AND source_type IN ('INTERVIEW_STATEMENT','SALES_NOTE','OPERATOR_NOTE','FEEDBACK_STATEMENT','SCREEN_SHARED_INFORMATION','DOCUMENT_EXISTENCE_OBSERVED')`,[input.sourceRecordId,id])).rows[0];if(!source)throw new DiagnosisError(422,'同じ案件の確認記録を指定してください。');await c.query(`UPDATE assessment_scope_clarifications SET status='RESOLVED',resolution_source_record_id=$3,resolved_by_user_id=$4,resolved_at=now(),updated_at=now() WHERE id=$1 AND diagnosis_case_id=$2`,[key,id,input.sourceRecordId,this.staff(a)]);await this.audit(c,id,a,'ResolveAssessmentScopeClarification',{clarification_id:key,resolution_source_record_id:input.sourceRecordId});});}
 async notRequired(id:string,key:string,a:Actor,input:{expectedVersion:number;reason:string}){if(!input.reason?.trim())throw new DiagnosisError(422,'不要と判断した理由を入力してください。');return this.tx(async c=>{await this.lockRouteC(c,id,a,input.expectedVersion);const r=await c.query(`UPDATE assessment_scope_clarifications SET status='NOT_REQUIRED',updated_at=now() WHERE id=$1 AND diagnosis_case_id=$2 AND status='OPEN' RETURNING id`,[key,id]);if(!r.rows.length)throw new DiagnosisError(409,'OPENの確認項目を指定してください。');await this.audit(c,id,a,'MarkAssessmentScopeClarificationNotRequired',{clarification_id:key,reason:input.reason.trim()});});}
 async read(id:string,a:Actor){this.staff(a);return this.tx(async c=>{await this.lockRouteC(c,id,a);const rows=(await c.query('SELECT * FROM assessment_scope_clarifications WHERE diagnosis_case_id=$1 ORDER BY created_at,id',[id])).rows;return{items:rows,open_items:rows.filter((x:any)=>x.status==='OPEN')};});}
}
