import {randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import {DiagnosisError,companyDisplayName,type Actor,type DiagnosisStatus} from '../domain/itManagementDiagnosis';
import {contentHash} from '../domain/diagnosisReport';
import type {HandoffSnapshot} from '../domain/diagnosisAssessment';
import {buildAssessmentHandoffSnapshot} from './assessmentHandoffSnapshot';
interface CaseRow {id:string;version:number;diagnosis_status:DiagnosisStatus;assessment_status:string;assessment_metadata_json:Record<string,unknown>;closed_at:Date|null;closed_by_user_id:string|null;organization_name:string}
interface Handoff {id:string;version:number;status:string;snapshot_json:HandoffSnapshot;snapshot_hash:string;report_id:string}
const commands={propose:{from:['NOT_PROPOSED'],to:'PROPOSED',name:'ProposeAssessment'},pending:{from:['PROPOSED'],to:'PENDING',name:'MarkAssessmentPending'},accept:{from:['PROPOSED','PENDING'],to:'ACCEPTED',name:'AcceptAssessment'},decline:{from:['PROPOSED','PENDING'],to:'DECLINED',name:'DeclineAssessment'}};
export class DiagnosisAssessmentRepo{
 constructor(private readonly pool:Pool){}
 private async tx<T>(work:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query('BEGIN');const out=await work(c);await c.query('COMMIT');return out;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private staff(actor:Actor){if(actor.kind!=='STAFF'||!actor.userId)throw new DiagnosisError(403,'スタッフによる操作が必要です。');return actor.userId;}
 private async lock(c:PoolClient,id:string,actor:Actor,expectedVersion?:number){this.staff(actor);const {rows}=await c.query<CaseRow>(`SELECT c.id,c.version,c.diagnosis_status,c.assessment_status,c.assessment_metadata_json,c.closed_at,c.closed_by_user_id,o.name AS organization_name FROM diagnosis_cases c JOIN organizations o ON o.id=c.organization_id WHERE c.id=$1 FOR UPDATE OF c`,[id]);const row=rows[0];if(!row)throw new DiagnosisError(404,'案件が見つかりません。');if(expectedVersion!==undefined&&row.version!==expectedVersion)throw new DiagnosisError(409,'内容が更新されています。再読み込みしてください。');return row;}
 private active(row:CaseRow){if(!['FEEDBACK_COMPLETED','CLOSED'].includes(row.diagnosis_status))throw new DiagnosisError(409,'経営フィードバック完了後の案件で操作してください。');}
 private async requireAssessmentRoute(c:PoolClient,id:string){const route=(await c.query<{route_code:string}>('SELECT route_code FROM management_feedback_decisions WHERE diagnosis_case_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0]?.route_code;if(route!=='DESIGN_ASSESSMENT')throw new DiagnosisError(409,'経営フィードバック後、設計Assessmentを検討する判断を人が記録してください。');}
 private async audit(c:PoolClient,id:string,actor:Actor,command:string,detail:unknown){await c.query('UPDATE diagnosis_cases SET version=version+1,updated_at=now() WHERE id=$1',[id]);await c.query(`INSERT INTO diagnosis_audit_logs(id,diagnosis_case_id,command,actor_type,actor_user_id,detail_json) VALUES($1,$2,$3,'STAFF',$4,$5)`,[randomUUID(),id,command,this.staff(actor),JSON.stringify(detail)]);}
 private async handoffs(c:PoolClient,id:string){return (await c.query<Handoff>('SELECT * FROM assessment_handoffs WHERE diagnosis_case_id=$1 ORDER BY version DESC',[id])).rows;}
 async lifecycle(id:string,actor:Actor,action:keyof typeof commands,expectedVersion:number,reason:string){return this.tx(async c=>{const row=await this.lock(c,id,actor,expectedVersion);this.active(row);await this.requireAssessmentRoute(c,id);const cmd=commands[action];if(!cmd.from.includes(row.assessment_status))throw new DiagnosisError(409,'このAssessment状態では操作できません。');const metadata={...row.assessment_metadata_json,[cmd.to]:{at:new Date().toISOString(),by:this.staff(actor),reason}};
 await c.query('UPDATE diagnosis_cases SET assessment_status=$2,assessment_metadata_json=$3 WHERE id=$1',[id,cmd.to,JSON.stringify(metadata)]);await this.audit(c,id,actor,cmd.name,{from:row.assessment_status,to:cmd.to,reason});});}
 async generate(id:string,actor:Actor,expectedVersion:number,reason:string){return this.tx(async c=>{const row=await this.lock(c,id,actor,expectedVersion);this.active(row);await this.requireAssessmentRoute(c,id);if(row.assessment_status!=='ACCEPTED')throw new DiagnosisError(409,'Assessment受注後にHandoffを作成してください。');const previous=(await this.handoffs(c,id))[0],snapshot=await buildAssessmentHandoffSnapshot(c,id,new Date().toISOString()),key=randomUUID(),version=(previous?.version??0)+1,hash=contentHash(snapshot);
 await c.query(`INSERT INTO assessment_handoffs(id,diagnosis_case_id,version,status,report_id,snapshot_json,snapshot_hash,created_by_user_id) VALUES($1,$2,$3,'READY',$4,$5,$6,$7)`,[key,id,version,snapshot.report.id,JSON.stringify(snapshot),hash,this.staff(actor)]);await this.audit(c,id,actor,'GenerateAssessmentHandoff',{handoff_id:key,version,snapshot_hash:hash,previous_handoff_id:previous?.id??null,reason});return {id:key,version};});}
 private async fresh(c:PoolClient,id:string,h:Handoff){if(contentHash(h.snapshot_json)!==h.snapshot_hash)throw new DiagnosisError(409,'Handoffのhashが一致しません。');const current=await buildAssessmentHandoffSnapshot(c,id,h.snapshot_json.generated_at);current.diagnosis_status=h.snapshot_json.diagnosis_status;if(contentHash(current)!==h.snapshot_hash)throw new DiagnosisError(409,'引継ぎ元の情報が変更されています。引継ぎ情報の新しい版を作成してください。');}
 async transfer(id:string,actor:Actor,key:string,expectedVersion:number,reason:string){return this.tx(async c=>{const row=await this.lock(c,id,actor,expectedVersion);this.active(row);await this.requireAssessmentRoute(c,id);const h=(await this.handoffs(c,id))[0];if(row.assessment_status!=='ACCEPTED'||!h||h.id!==key||h.status!=='READY')throw new DiagnosisError(409,'最新のREADY Handoffを指定してください。');await this.fresh(c,id,h);
 await c.query(`UPDATE assessment_handoffs SET status='TRANSFERRED',transferred_by_user_id=$2,transferred_at=now(),updated_at=now() WHERE id=$1`,[key,this.staff(actor)]);await this.audit(c,id,actor,'TransferAssessmentHandoff',{handoff_id:key,snapshot_hash:h.snapshot_hash,confirmation_item_ids:h.snapshot_json.assessment_confirmation_items.map(i=>i.id),reason});});}
 private async eligibility(c:PoolClient,row:CaseRow,h?:Handoff){
  if(row.diagnosis_status==='CLOSED')return {eligible:false,reason:'無料診断は人が記録した次の判断により完了しています。'};
  if(row.diagnosis_status!=='FEEDBACK_COMPLETED')return {eligible:false,reason:'経営フィードバックと次の判断を記録してください。'};
  const decision=(await c.query('SELECT route_code FROM management_feedback_decisions WHERE diagnosis_case_id=$1 ORDER BY version DESC LIMIT 1',[row.id])).rows[0];
  return {eligible:false,reason:decision?.route_code==='FOCUSED_CONFIRMATION'?'必要な追加確認を行い、次の進め方を改めて判断してください。':'次の進め方を人が記録すると、無料診断の完了・継続が決まります。'};
 }
 async close(id:string,actor:Actor,expectedVersion:number,reason:string){return this.tx(async c=>{const row=await this.lock(c,id,actor,expectedVersion);if(row.diagnosis_status==='CLOSED')return;throw new DiagnosisError(409,(await this.eligibility(c,row)).reason);});}
 async read(id:string,actor:Actor){return this.tx(async c=>{const row=await this.lock(c,id,actor),history=await this.handoffs(c,id),latest=history[0],guard=await this.eligibility(c,row,latest);
 const {rows:audit}=await c.query(`SELECT command,actor_type,actor_user_id,detail_json,created_at FROM diagnosis_audit_logs WHERE diagnosis_case_id=$1 AND command IN ('ProposeAssessment','MarkAssessmentPending','AcceptAssessment','DeclineAssessment','GenerateAssessmentHandoff','TransferAssessmentHandoff','CloseDiagnosisCase','RecordManagementFeedbackDecision') ORDER BY created_at,id`,[id]);
 const {rows:transitions}=await c.query('SELECT from_status,to_status,command,actor_type,actor_user_id,created_at FROM case_transitions WHERE diagnosis_case_id=$1 ORDER BY created_at,id',[id]);
 const route=(await c.query('SELECT route_code FROM management_feedback_decisions WHERE diagnosis_case_id=$1 ORDER BY version DESC LIMIT 1',[id])).rows[0]?.route_code??null;
  return {...row,decision_route:route,organization_display_name:companyDisplayName(row.organization_name),provider_display_name:'atLIB株式会社',handoffs:history,latest_handoff:latest??null,close_eligibility:guard,current_next_action:route==='DESIGN_ASSESSMENT'&&['CLOSED','FEEDBACK_COMPLETED'].includes(row.diagnosis_status)?({NOT_PROPOSED:'設計Assessmentの提案を検討できます。受注は別の人操作です。',PROPOSED:'設計Assessmentの回答を確認してください。',PENDING:'設計Assessmentの回答待ちです。',DECLINED:'設計Assessmentの辞退を記録しています。',ACCEPTED:latest?.status==='TRANSFERRED'?'設計Assessmentへの引渡しを記録しています。':'設計Assessmentへの引継ぎ情報を作成・引渡ししてください。'}[row.assessment_status]??'設計Assessmentの状況を確認してください。'):row.diagnosis_status==='CLOSED'?'無料診断は完了しています。記録した次の行動を確認してください。':row.diagnosis_status==='DIAGNOSIS_IN_PROGRESS'?'追加確認を行い、分析・経営フィードバック後に次の進め方を改めて判断してください。':'経営フィードバック後、次の進め方を人が記録してください。',audit,transitions};});}
}
