import type {PoolClient} from 'pg';
import {progressiveReuseReadModel} from './progressiveReuseReadModel';
import {buildReportContext} from './reportContext';
import {AREAS,LENSES} from '../domain/diagnosisReview';
export async function managementAnalysisReadModel(c:PoolClient,id:string){
 const reuse=await progressiveReuseReadModel(c,id),report=await c.query('SELECT id FROM diagnosis_futures WHERE diagnosis_case_id=$1 AND is_current',[id]),reportContext=report.rows.length?await buildReportContext(c,id):null;
 const approved=(await c.query(`SELECT i.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('source_ref_type',s.source_ref_type,'source_ref_id',s.source_ref_id,'source_revision_id',s.source_revision_id,'relation',s.relation)) FROM insight_sources s WHERE s.diagnosis_insight_id=i.id),'[]'::jsonb) AS source_refs FROM diagnosis_insights i WHERE i.diagnosis_case_id=$1 AND i.review_status='HUMAN_APPROVED' ORDER BY i.created_at,i.id`,[id])).rows;
 const proposals=(await c.query(`SELECT p.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('source_ref_type',s.source_ref_type,'source_ref_id',s.source_ref_id,'source_revision_id',s.source_revision_id,'relation',s.relation)) FROM ai_proposal_sources s WHERE s.ai_proposal_id=p.id),'[]'::jsonb) AS source_refs FROM ai_proposals p JOIN ai_executions e ON e.id=p.ai_execution_id WHERE p.diagnosis_case_id=$1 AND e.process_type='POST_DIAGNOSIS_STRUCTURER' AND e.status='SUCCEEDED' AND e.validation_status='VALID' AND p.status IN ('GENERATED','UNDER_REVIEW') AND p.title<>'[REDACTED]' ORDER BY p.created_at,p.display_order`,[id])).rows;
 const raw=(await c.query('SELECT id,source_type,content,created_at FROM source_records WHERE diagnosis_case_id=$1',[id])).rows;
 const hearing=(await c.query(`SELECT r.id,rv.id AS revision_id,r.question_code,r.question_version,rv.current_json,rv.recorded_at,rv.version=r.version AS is_current FROM diagnosis_hearing_records r JOIN diagnosis_hearing_record_revisions rv ON rv.hearing_record_id=r.id AND rv.diagnosis_case_id=r.diagnosis_case_id WHERE r.diagnosis_case_id=$1`,[id])).rows;
 const entries=[...reuse.known,...reuse.unknown,...reuse.hypotheses],source=(r:any)=>{if(r.source_ref_type==='HEARING_RECORD'){const cited=hearing.find(x=>x.id===r.source_ref_id&&x.revision_id===r.source_revision_id),current=hearing.find(x=>x.id===r.source_ref_id&&x.is_current);return {type:r.source_ref_type,id:r.source_ref_id,source_revision_id:r.source_revision_id,relation:r.relation,label:'Hearing response',question_code:cited?.question_code??null,question_version:cited?.question_version??null,referenced_answer:cited?.current_json??null,current_answer:current?.current_json??null,recorded_at:cited?.recorded_at??null,is_historical_revision:!!cited&&!cited.is_current};}const e=entries.filter(x=>x.origin.kind===r.source_ref_type&&x.origin.id===r.source_ref_id),s=r.source_ref_type==='SOURCE_RECORD'?raw.find(x=>x.id===r.source_ref_id):null;return {type:r.source_ref_type,id:r.source_ref_id,source_revision_id:null,relation:r.relation,label:r.source_ref_type==='SURVEY_RESPONSE'?'Web survey response':'Source record',text:e.length?e.map(x=>x.text).join('\n'):s?.content??null,recorded_at:e[0]?.recorded_at??s?.created_at??null};};
 const items=[...approved.map(i=>({...i,approval:'HUMAN_APPROVED' as const})),...proposals.map(p=>({...p.content_json,id:p.id,approval:'PROPOSAL' as const,source_refs:p.source_refs}))].map(i=>({id:i.id,title:i.title,content:i.content,semantic_type:i.semantic_type,unknown_type:i.unknown_type,area_tag:i.area_tag,improvement_lens:i.improvement_lens,diagnosis_theme_id:i.diagnosis_theme_id,approval:i.approval,why_connection:i.approval==='HUMAN_APPROVED'?reportContext?.insights.find(x=>x.id===i.id)?.why_connection??null:null,sources:(i.source_refs as any[]).map(source)}));
 const directions=items.filter(i=>i.semantic_type==='KAIZEN_DIRECTION'),cells=AREAS.flatMap(area=>LENSES.map(lens=>({area,lens,items:directions.filter(i=>i.area_tag===area&&i.improvement_lens===lens)}))).filter(cell=>cell.items.length),decision=(await c.query(`SELECT route_code,material_decision,next_action,decided_by_user_id,decided_at,version FROM management_feedback_decisions WHERE diagnosis_case_id=$1 ORDER BY version DESC LIMIT 1`,[id])).rows[0]??null;
 return {reuse,items,lens:{cells,unclassified:directions.filter(i=>!AREAS.includes(i.area_tag)||!LENSES.includes(i.improvement_lens))},report_context:reportContext,decision};
}
