import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { contentHash, manualReport, storeReport, type ReportContext } from '../domain/diagnosisReport';
import { intakeAnswerEnvelopeSchema } from '../domain/freeDiagnosisRuleBasedV1';
import { projectIntakeSemantics } from '../domain/intakeSemanticProjection';
import { runFinalRule } from '../domain/finalRuleEngine';
import { RuleBasedV1Error } from '../domain/freeDiagnosisRuleBasedV1';
import { hearingAnswerDisplayLabel } from '../domain/structuredHearing';

type Semantic = 'OBSERVATION'|'UNKNOWN'|'HYPOTHESIS'|'GAP_CANDIDATE'|'ROOT_CAUSE_HYPOTHESIS'|'KAIZEN_DIRECTION'|'EVIDENCE_CANDIDATE';
const futureLabels: Record<string, string> = {
  HEADCOUNT_GROWTH: '人員を増やす', SITE_CHANGE: '拠点を変える・増やす', NEW_BUSINESS: '新しい事業を始める', ORG_CHANGE: '組織を変える', IPO_PREPARATION: '上場準備を進める', WORKSTYLE_CHANGE: '働き方を変える', BUSINESS_EXPANSION: '事業を広げる', LEAN_SCALING: '少人数で成長・運営する', STABILITY_EFFICIENCY: '安定・効率を高める', NO_MAJOR_CHANGE: '大きな変化は予定していない', SUPPORT_CHANGE: '変化を支えたい', IMPROVE_PRODUCTIVITY: '生産性を高めたい', PROTECT_BUSINESS: '事業を守りたい', ENABLE_MANAGEMENT_DECISION: '経営判断を支えたい', STRATEGIC_IT_USE: 'ITを戦略的に活かしたい', STABILIZE_IT_OPERATION: 'IT運営を安定させたい', OPTIMIZE_IT_INVESTMENT: 'IT投資を見直したい', UNDECIDED: 'まだ決めていない', OTHER: 'その他',
};
export class Vs1ReviewReportFeedbackRepo {
  constructor(private readonly pool: Pool) {}
  private async audit(caseId:string, actor:string, command:string, detail:unknown){await this.pool.query(`INSERT INTO it_management_diagnosis_case_v2_audit(id,case_id,command,actor_user_id,detail_json) VALUES($1,$2,$3,$4,$5)`,[randomUUID(),caseId,command,actor,JSON.stringify(detail)]);}
  async project(caseId:string, executionId:string, actor:string){
    const {rows}=await this.pool.query<any>('SELECT input_snapshot_json FROM rule_analysis_execution WHERE id=$1 AND case_id=$2 AND analysis_stage=\'FINAL\'',[executionId,caseId]); if(!rows[0]) throw new RuleBasedV1Error(404,'FINAL_RULE_EXECUTION_NOT_FOUND');
    const snap=typeof rows[0].input_snapshot_json==='string'?JSON.parse(rows[0].input_snapshot_json):rows[0].input_snapshot_json, final=runFinalRule({intake:projectIntakeSemantics(snap.intake.map((x:any)=>intakeAnswerEnvelopeSchema.parse(x))),answers:snap.hearing,knowledgeStates:snap.hearingKnowledgeStates ?? []});
    const add=async(type:Semantic,content:string,unknownType:string|null=null)=>{const id=randomUUID();await this.pool.query(`INSERT INTO diagnosis_insights(id,it_management_diagnosis_case_v2_id,semantic_type,title,content,unknown_type,review_status,created_by,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,'HUMAN_APPROVED','HUMAN',$7)`,[id,caseId,type,type,content,unknownType,actor]);await this.pool.query(`INSERT INTO insight_sources(diagnosis_insight_id,it_management_diagnosis_case_v2_id,source_ref_type,source_ref_id,relation) VALUES($1,$2,'VS1_RULE_EXECUTION',$3,'SUPPORTS')`,[id,caseId,executionId]);return id;};
    for(const x of final.currentUnderstanding) await add('OBSERVATION',`確認した状態：${hearingAnswerDisplayLabel(x.answerValue)}`);
    for(const x of final.remainingUnknown) await add('UNKNOWN','今回まだ確認できていない事項があります。','NOT_YET_CONFIRMED');
    for(const x of final.gapPossibilities) await add('GAP_CANDIDATE',x.statement);
    for(const x of final.improvementOpportunities) await add('KAIZEN_DIRECTION',x.statement);
    for(const x of final.evidenceCandidates) await add('EVIDENCE_CANDIDATE',x.purpose);
    await this.audit(caseId,actor,'CompleteHumanReviewProjection',{from_state:'HUMAN_REVIEW_REQUIRED',to_state:'HUMAN_REVIEW_REQUIRED',rule_execution_id:executionId}); return final;
  }
  async context(caseId:string):Promise<ReportContext>{
    const c=await this.pool.query<any>('SELECT c.id,co.name FROM it_management_diagnosis_case_v2 c JOIN company co ON co.id=c.company_id WHERE c.id=$1',[caseId]);if(!c.rows[0])throw new RuleBasedV1Error(404,'CASE_NOT_FOUND');
    const intake=(await this.pool.query<any>('SELECT raw_value_json FROM hearing_intake_response_v2 WHERE case_id=$1',[caseId])).rows.map(x=>intakeAnswerEnvelopeSchema.parse(x.raw_value_json));
    const future=intake.filter((x:any)=>x.questionCode==='Q2'||x.questionCode==='Q3').flatMap((x:any)=>Array.isArray(x.answerValue)?x.answerValue:[]).map((value:string)=>futureLabels[value] ?? 'その他'); const text=future.length?`回答時点で伺った今後の会社の変化・ITに期待する状態：${future.join(' / ')}`:'目指している会社の姿は現時点で未確認です。';
    const insights=(await this.pool.query<any>(`SELECT id,version,semantic_type,title,content,unknown_type,area_tag,improvement_lens FROM diagnosis_insights WHERE it_management_diagnosis_case_v2_id=$1 AND review_status='HUMAN_APPROVED' ORDER BY created_at`,[caseId])).rows.map((i:any)=>({...i,report_text:`${i.content}`}));
    // A preliminary scope is a customer-facing next-step option, not a FACT or an
    // automatic recommendation. It is included only after the human review has
    // deliberately reached the assessment-structure stage.
    const scope=(await this.pool.query<any>(`SELECT id,suggested_base_price FROM assessment_structure_suggestion WHERE case_id=$1 AND stage='PRELIMINARY' ORDER BY created_at DESC LIMIT 1`,[caseId])).rows[0];
    const assessment_confirmation_items=scope?[{id:scope.id,title:'さらに詳しく確認する場合',purpose:'今回の診断では、実際の業務・情報・ITの状況を横断して確認する価値があると整理されました。有料IT経営アセスメントでは、事実に基づいて改善すべき点を明らかにします。'+(scope.suggested_base_price!=null?` IT経営アセスメント：${Number(scope.suggested_base_price).toLocaleString('ja-JP')}円（税別）。`:''),priority:1,status:'OPEN' as const,report_text:'さらに詳しく確認する場合：実際の業務・情報・ITの状況を確認し、事実に基づいて改善すべき点を明らかにします。'+(scope.suggested_base_price!=null?` IT経営アセスメント：${Number(scope.suggested_base_price).toLocaleString('ja-JP')}円（税別）。`:'')}]:[];
    return {organization_display_name:c.rows[0].name,provider_display_name:'atLIB株式会社',future:{id:caseId,version:1,statement:text,time_horizon:null,intent_status:'SURVEY_STATED',report_text:text},insights,assessment_confirmation_items};
  }
  async draft(caseId:string,actor:string){const context=await this.context(caseId), output=manualReport(context), id=randomUUID();const r=await this.pool.query<any>('SELECT COALESCE(MAX(version),0)+1 v FROM diagnosis_reports WHERE it_management_diagnosis_case_v2_id=$1',[caseId]);await this.pool.query(`INSERT INTO diagnosis_reports(id,it_management_diagnosis_case_v2_id,version,status,content_json,context_json,context_hash,prompt_version,policy_version,created_by,created_by_user_id) VALUES($1,$2,$3,'REVIEW_REQUIRED',$4,$5,$6,'human-projection-v1','vs1','HUMAN',$7)`,[id,caseId,r.rows[0].v,JSON.stringify(storeReport(output)),JSON.stringify(context),contentHash(context),actor]);await this.pool.query(`UPDATE it_management_diagnosis_case_v2 SET status='REPORT_REVIEW_REQUIRED',version=version+1 WHERE id=$1`,[caseId]);await this.audit(caseId,actor,'CreateReportDraft',{from_state:'HUMAN_REVIEW_REQUIRED',to_state:'REPORT_REVIEW_REQUIRED',report_id:id,report_version:r.rows[0].v});return{id,version:r.rows[0].v};}
  async getReport(caseId:string,reportId:string){const row=(await this.pool.query<any>('SELECT id,version,status,content_json,snapshot_json FROM diagnosis_reports WHERE id=$1 AND it_management_diagnosis_case_v2_id=$2',[reportId,caseId])).rows[0];if(!row)throw new RuleBasedV1Error(404,'REPORT_NOT_FOUND');return {id:row.id,version:row.version,status:row.status,content:row.content_json,snapshot:row.snapshot_json};}
  async approve(caseId:string,reportId:string,actor:string){const q=await this.pool.query<any>('SELECT * FROM diagnosis_reports WHERE id=$1 AND it_management_diagnosis_case_v2_id=$2',[reportId,caseId]);const r=q.rows[0];if(!r||r.status!=='REVIEW_REQUIRED')throw new RuleBasedV1Error(409,'REPORT_NOT_REVIEWABLE');const snapshot={context:r.context_json,content_hash:contentHash(r.content_json),approved_by:actor,approved_at:new Date().toISOString()};await this.pool.query(`UPDATE diagnosis_reports SET status='APPROVED',snapshot_json=$1,approved_by_user_id=$2,approved_at=now() WHERE id=$3`,[JSON.stringify(snapshot),actor,reportId]);await this.pool.query(`UPDATE it_management_diagnosis_case_v2 SET status='REPORT_APPROVED',version=version+1 WHERE id=$1`,[caseId]);await this.audit(caseId,actor,'ApproveReport',{from_state:'REPORT_REVIEW_REQUIRED',to_state:'REPORT_APPROVED',report_id:reportId,approval_snapshot_hash:contentHash(snapshot)});}
  async deliver(caseId:string,reportId:string,actor:string){const r=(await this.pool.query<any>('SELECT status,snapshot_json FROM diagnosis_reports WHERE id=$1 AND it_management_diagnosis_case_v2_id=$2',[reportId,caseId])).rows[0];if(!r||r.status!=='APPROVED'||!r.snapshot_json)throw new RuleBasedV1Error(409,'REPORT_NOT_APPROVED');await this.pool.query(`UPDATE diagnosis_reports SET status='DELIVERED',delivered_at=now() WHERE id=$1`,[reportId]);await this.pool.query(`UPDATE it_management_diagnosis_case_v2 SET status='FEEDBACK_PENDING',feedback_report_id=$2,version=version+1 WHERE id=$1`,[caseId,reportId]);await this.audit(caseId,actor,'DeliverReport',{from_state:'REPORT_APPROVED',to_state:'FEEDBACK_PENDING',report_id:reportId,approval_snapshot_hash:contentHash(r.snapshot_json)});}
  async startFeedback(caseId:string,actor:string){const r=await this.pool.query<any>(`UPDATE it_management_diagnosis_case_v2 SET feedback_started_at=now(),feedback_started_by_user_id=$2,version=version+1 WHERE id=$1 AND status='FEEDBACK_PENDING' AND feedback_started_at IS NULL RETURNING feedback_report_id`,[caseId,actor]);if(!r.rows[0])throw new RuleBasedV1Error(409,'FEEDBACK_NOT_STARTABLE');await this.audit(caseId,actor,'StartFeedback',{from_state:'FEEDBACK_PENDING',to_state:'FEEDBACK_PENDING',report_id:r.rows[0].feedback_report_id});}
  async decide(caseId:string,actor:string,input:{route:'DIRECT_ACT'|'FOCUSED_CONFIRMATION'|'DESIGN_ASSESSMENT'|'STOP_HOLD';materialDecision:string;nextAction:string}){const c=(await this.pool.query<any>('SELECT * FROM it_management_diagnosis_case_v2 WHERE id=$1',[caseId])).rows[0];if(!c||c.status!=='FEEDBACK_PENDING'||!c.feedback_started_at||!c.feedback_report_id)throw new RuleBasedV1Error(409,'FEEDBACK_NOT_READY');const report=(await this.pool.query<any>('SELECT * FROM diagnosis_reports WHERE id=$1 AND status=\'DELIVERED\'',[c.feedback_report_id])).rows[0];const snapshot={report:{id:report.id,version:report.version,content_hash:contentHash(report.content_json),approval_snapshot_hash:contentHash(report.snapshot_json)},decision:input};const prev=(await this.pool.query<any>('SELECT COALESCE(MAX(version),0) v FROM management_feedback_decisions WHERE it_management_diagnosis_case_v2_id=$1',[caseId])).rows[0].v;const decisionId=randomUUID();await this.pool.query(`INSERT INTO management_feedback_decisions(id,it_management_diagnosis_case_v2_id,version,route_code,material_decision,next_action,context_snapshot_json,context_hash,decided_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[decisionId,caseId,prev+1,input.route,input.materialDecision,input.nextAction,JSON.stringify(snapshot),contentHash(snapshot),actor]);const status=input.route==='FOCUSED_CONFIRMATION'?'HEARING_IN_PROGRESS':'CLOSED';await this.pool.query(`UPDATE it_management_diagnosis_case_v2 SET status=$2,feedback_completed_at=now(),version=version+1 WHERE id=$1`,[caseId,status]);await this.audit(caseId,actor,'RecordManagementFeedbackDecision',{from_state:'FEEDBACK_PENDING',to_state:status,feedback_decision_id:decisionId,report_id:report.id,route:input.route});return{status};}
}
