/* Builds only a reviewed allowlist context. It never runs SQL or Docker. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const fail=(m)=>{throw Error(`MIGRATION_ALLOWLIST_INVALID:${m}`)};
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const args=Object.fromEntries(process.argv.slice(2).map((x,i,a)=>x.startsWith('--')?[x.slice(2),a[i+1]]:[]).filter(x=>x.length));
function verify(root,manifestPath){const m=JSON.parse(fs.readFileSync(manifestPath,'utf8'));if(m.status!=='APPROVED_FOR_ARTIFACT_GENERATION'||m.artifact_generation?.permitted!==true)fail('MANIFEST_NOT_APPROVED');const l=m.ledger_source??{},snap=path.resolve(root,l.snapshot_path??'');if(!l.original_json_sha256||!fs.existsSync(snap)||hash(snap)!==l.original_json_sha256)fail('LEDGER_SNAPSHOT_HASH');const ledger=JSON.parse(fs.readFileSync(snap,'utf8'));if(!Array.isArray(ledger)||ledger.length!==l.entry_count||!ledger.every(x=>typeof x.filename==='string'&&typeof x.applied_at==='string'))fail('LEDGER_SNAPSHOT_SHAPE');const applied=new Set(ledger.map(x=>x.filename)),names=m.migrations?.map(x=>x.filename)??[],expected=m.expected_unapplied_filenames??[],migrationDir=path.join(root,'migrations');const sqlName=/^[0-9]+_[a-z0-9_]+\.sql$/;const pending=fs.readdirSync(migrationDir).filter(x=>sqlName.test(x)&&!applied.has(x)).sort();if(new Set(names).size!==names.length||new Set(expected).size!==expected.length||names.slice().sort().join('\n')!==expected.slice().sort().join('\n'))fail('MANIFEST_FILENAMES');if(pending.join('\n')!==expected.slice().sort().join('\n'))fail('TREE_PENDING_FILENAMES');for(const x of m.migrations){if(applied.has(x.filename))fail(`ALREADY_APPLIED:${x.filename}`);const p=path.join(migrationDir,x.filename);if(!sqlName.test(x.filename)||!fs.existsSync(p)||hash(p)!==x.sha256)fail(`SQL_HASH:${x.filename}`)}return m}
function copyRequired(source,target){if(!fs.existsSync(source))fail(`BUILD_INPUT_MISSING:${path.basename(source)}`);fs.cpSync(source,target,{recursive:true});}
function main(){const root=path.resolve(args.root??'.'),manifest=path.resolve(root,args.manifest??'migration-allowlists/staging-p2-10.candidate.json'),out=path.resolve(root,args.output??'migration-allowlist-artifact');const m=verify(root,manifest);if(args['reviewed-sha']!==m.source_commit)fail('REVIEWED_SHA');if(fs.existsSync(out))fail('OUTPUT_EXISTS');const temporary=`${out}.tmp-${process.pid}`;if(fs.existsSync(temporary))fail('TEMP_OUTPUT_EXISTS');try{fs.mkdirSync(path.join(temporary,'migrations'),{recursive:true});for(const x of m.migrations)fs.copyFileSync(path.join(root,'migrations',x.filename),path.join(temporary,'migrations',x.filename));fs.copyFileSync(manifest,path.join(temporary,'manifest.json'));copyRequired(path.join(root,'package.json'),path.join(temporary,'package.json'));copyRequired(path.join(root,'package-lock.json'),path.join(temporary,'package-lock.json'));copyRequired(path.join(root,'dist'),path.join(temporary,'dist'));copyRequired(path.join(root,'Dockerfile.migration-allowlist'),path.join(temporary,'Dockerfile'));fs.renameSync(temporary,out);console.log(JSON.stringify({event:'migration_allowlist_context_built',filenames:m.migrations.map(x=>x.filename)}));}catch(error){fs.rmSync(temporary,{recursive:true,force:true});throw error}}
if(require.main===module)try{main()}catch(e){console.error(e.message);process.exitCode=1}
module.exports={verify};
