/* Post-migration verifier. Requires BEGIN READ ONLY and cannot execute migrations. */
const {Pool}=require('pg');
const fail=(message)=>{throw Error(`IT_MANAGEMENT_RELEASE_VERIFY_FAILED:${message}`)};
const args=Object.fromEntries(process.argv.slice(2).flatMap((v,i,a)=>v.startsWith('--')&&a[i+1]?[[v.slice(2),a[i+1]]:[]));
const must=(ok,label)=>{if(!ok)fail(label)};
const migrationFiles=['028_free_diagnosis_current_design_v1_phase1_draft.sql','029_vs1_report_feedback_shared_artifacts.sql','030_sales_activity_marketing_attribution.sql','031_public_customer_self_submission.sql','032_sales_activity_referral_person_name.sql'];
const columns=[['hearing_statement_v2','structured_answer_json'],['rule_analysis_execution','analysis_stage'],['rule_analysis_execution','input_snapshot_json'],['sales_activity','acquisition_source_type'],['sales_activity','acquisition_source_name'],['sales_activity','utm_source'],['sales_activity','utm_medium'],['sales_activity','utm_campaign'],['sales_activity','utm_content'],['sales_activity','utm_term'],['sales_activity','landing_url'],['sales_activity','referrer'],['sales_activity','referral_person_name'],['diagnosis_reports','it_management_diagnosis_case_v2_id'],['management_feedback_decisions','it_management_diagnosis_case_v2_id'],['it_management_public_self_submission','idempotency_key']];
const constraints=['diagnosis_insights_exactly_one_case','insight_sources_exactly_one_case','insight_sources_vs1_insight_case_fkey','insight_sources_source_ref_type_check','insight_sources_vs1_source_owner_check','human_reviews_exactly_one_case','diagnosis_reports_exactly_one_case','management_feedback_decisions_exactly_one_case','it_management_diagnosis_case_v2_status_check','sales_activity_acquisition_source_type_check','sales_activity_acquisition_source_pair_check'];
const indexes=['sales_activity_acquisition_source_name_idx','sales_activity_utm_campaign_idx','diagnosis_reports_vs1_case_version','management_feedback_vs1_case_version','it_management_diagnosis_case_v2_audit_case_idx','it_management_public_self_submission_case_idx'];
async function run(){
 if(process.env.PREFLIGHT_READ_ONLY!=='true')fail('PREFLIGHT_READ_ONLY_ENV');for(const key of ['DB_NAME','DB_USER','DB_PASSWORD'])if(!process.env[key])fail(`MISSING_${key}`);
 const pool=new Pool({host:process.env.DB_SOCKET_PATH||process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT??5432),database:process.env.DB_NAME,user:process.env.DB_USER,password:process.env.DB_PASSWORD,max:1});const c=await pool.connect();
 try{await c.query('BEGIN READ ONLY');const q=(sql,values=[])=>c.query(sql,values);const identity=(await q("SELECT current_database() database,current_setting('server_version') version,current_setting('transaction_read_only') ro")).rows[0];must(identity.database==='sales_tools'&&/^16\./.test(identity.version)&&identity.ro==='on','IDENTITY_OR_READ_ONLY');
  const ledger=(await q('SELECT filename,count(*)::int count FROM schema_migrations GROUP BY filename')).rows;const counts=new Map(ledger.map(r=>[r.filename,Number(r.count)]));for(const f of migrationFiles)must(counts.get(f)===1,`LEDGER:${f}`);must(!ledger.some(r=>{const m=/^(\d+)_/.exec(r.filename);return m&&Number(m[1])>32;}),'UNEXPECTED_LEDGER');
  const col=(await q("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema='public' AND (table_name||'.'||column_name)=ANY($1::text[])",[columns.map(x=>`${x[0]}.${x[1]}`)])).rows;must(col.length===columns.length,'COLUMNS');
  const con=(await q("SELECT conname FROM pg_constraint WHERE connamespace='public'::regnamespace AND conname=ANY($1::text[])",[constraints])).rows;must(con.length===constraints.length,'CONSTRAINTS');
  const idx=(await q("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname=ANY($1::text[])",[indexes])).rows;must(idx.length===indexes.length,'INDEXES');
  const generated=(await q("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='insight_sources' AND column_name=ANY($1::text[]) AND is_generated='ALWAYS'",[['vs1_intake_response_id','vs1_hearing_statement_id','vs1_rule_execution_id']])).rows;must(generated.length===3,'GENERATED_COLUMNS');
  const composite=(await q("SELECT pg_get_constraintdef(oid) definition FROM pg_constraint WHERE conrelid='insight_sources'::regclass AND contype='f'")).rows.map(r=>r.definition).join('\n');for(const key of ['vs1_intake_response_id, it_management_diagnosis_case_v2_id','vs1_hearing_statement_id, it_management_diagnosis_case_v2_id','vs1_rule_execution_id, it_management_diagnosis_case_v2_id'])must(composite.includes(key),`COMPOSITE_FK:${key}`);
  const privileges=(await q("SELECT t table_name,has_table_privilege('sales_tools_app',format('public.%I',t.table_name),'SELECT,INSERT,UPDATE,DELETE') ok FROM unnest($1::text[]) t(table_name)",[['sales_activity','diagnosis_insights','insight_sources','human_reviews','diagnosis_reports','management_feedback_decisions','it_management_public_self_submission']])).rows;must(privileges.every(r=>r.ok),'RUNTIME_DML');
  const dual=(await q("SELECT (SELECT count(*) FROM diagnosis_insights WHERE num_nonnulls(diagnosis_case_id,it_management_diagnosis_case_v2_id)<>1)+(SELECT count(*) FROM insight_sources WHERE num_nonnulls(diagnosis_case_id,it_management_diagnosis_case_v2_id)<>1)+(SELECT count(*) FROM human_reviews WHERE num_nonnulls(diagnosis_case_id,it_management_diagnosis_case_v2_id)<>1)+(SELECT count(*) FROM diagnosis_reports WHERE num_nonnulls(diagnosis_case_id,it_management_diagnosis_case_v2_id)<>1)+(SELECT count(*) FROM management_feedback_decisions WHERE num_nonnulls(diagnosis_case_id,it_management_diagnosis_case_v2_id)<>1) bad")).rows[0];must(Number(dual.bad)===0,'LEGACY_OWNERSHIP');
  const sales=(await q('SELECT count(*)::bigint count,count(*) FILTER (WHERE referral_person_name IS NOT NULL)::bigint referral_set FROM sales_activity')).rows[0];if(args['minimum-sales-activity-count'])must(BigInt(sales.count)>=BigInt(args['minimum-sales-activity-count']),'SALES_ACTIVITY_COMPATIBILITY');
  await c.query('ROLLBACK');console.log(JSON.stringify({event:'it_management_release_post_verify_passed',database:identity.database,serverVersion:identity.version,salesActivityCount:String(sales.count),referralPersonNameSet:String(sales.referral_set)}));
 }catch(e){try{await c.query('ROLLBACK')}catch{};throw e;}finally{c.release();await pool.end();}
}
if(require.main===module)run().catch(e=>{console.error(JSON.stringify({event:'it_management_release_post_verify_failed',reason:e.message}));process.exitCode=1;});
