import type { QueryResult } from 'pg';
import { deletionPostTickReconciliationSql, type ReconciliationWindow } from './deletionPostTickReconciliationVerifier';

type Client={query(sql:string,values?:readonly unknown[]):Promise<unknown>;release():void}; type Pool={connect():Promise<Client>}; type Row=Record<string,unknown>;
export type WindowDiagnosticPhase='CONNECT'|'BEGIN_READ_ONLY'|'SET_STATEMENT_TIMEOUT'|'WINDOW_OUTCOME_SQL'|'WINDOW_OUTCOME_ROW_SHAPE'|'WINDOW_FAILURE_SQL'|'WINDOW_FAILURE_ROW_SHAPE'|'PROCESSED_SCOPE_SQL'|'PROCESSED_SCOPE_ROW_SHAPE'|'ROLLBACK'|'POOL_CLOSE';
export class WindowDiagnosticError extends Error { constructor(readonly phase:WindowDiagnosticPhase){super('DELETION_RECONCILIATION_WINDOW_DIAGNOSTIC_FAILED');} }
const fail=(phase:WindowDiagnosticPhase):never=>{throw new WindowDiagnosticError(phase);};
function keyed(result:unknown,key:string):void { const rows=(result as QueryResult<Row>)?.rows; if(!Array.isArray(rows))fail(key==='status'?'WINDOW_OUTCOME_ROW_SHAPE':key==='failure_code'?'WINDOW_FAILURE_ROW_SHAPE':'PROCESSED_SCOPE_ROW_SHAPE'); for(const row of rows){if(Object.keys(row).sort().join(',')!==[key,'count'].sort().join(',')||typeof row[key]!=='string'||typeof row.count!=='string')fail(key==='status'?'WINDOW_OUTCOME_ROW_SHAPE':key==='failure_code'?'WINDOW_FAILURE_ROW_SHAPE':'PROCESSED_SCOPE_ROW_SHAPE');} }
/** Runs the exact three P2-54 window SQL statements and emits phase-only evidence. */
export async function diagnoseDeletionReconciliationWindow(pool:Pool,window:ReconciliationWindow):Promise<'PROCESSED_SCOPE_ROW_SHAPE'> { const values=[window.start_utc,window.end_utc,'system:scheduler-deletion-worker'] as const;let client:Client;try{client=await pool.connect();}catch{return fail('CONNECT');}let begun=false;let phase:WindowDiagnosticPhase='BEGIN_READ_ONLY';try{await client.query(deletionPostTickReconciliationSql.BEGIN_READ_ONLY);begun=true;phase='SET_STATEMENT_TIMEOUT';await client.query(deletionPostTickReconciliationSql.SET_STATEMENT_TIMEOUT);phase='WINDOW_OUTCOME_SQL';const outcome=await client.query(deletionPostTickReconciliationSql.WINDOW_OUTCOME_COUNTS,values);phase='WINDOW_OUTCOME_ROW_SHAPE';keyed(outcome,'status');phase='WINDOW_FAILURE_SQL';const failure=await client.query(deletionPostTickReconciliationSql.WINDOW_FAILURE_COUNTS,values);phase='WINDOW_FAILURE_ROW_SHAPE';keyed(failure,'failure_code');phase='PROCESSED_SCOPE_SQL';const scope=await client.query(deletionPostTickReconciliationSql.PROCESSED_SCOPE_CLASS_COUNTS,values);phase='PROCESSED_SCOPE_ROW_SHAPE';keyed(scope,'data_class');phase='ROLLBACK';await client.query(deletionPostTickReconciliationSql.ROLLBACK);begun=false;return 'PROCESSED_SCOPE_ROW_SHAPE';}catch(error){if(begun){try{await client.query(deletionPostTickReconciliationSql.ROLLBACK);}catch{phase='ROLLBACK';}}if(error instanceof WindowDiagnosticError)throw error;return fail(phase);}finally{client.release();}}
